part of 'config.dart';

abstract class AppThemes {
  static ThemeData lightTheme = ThemeData(
    applyElevationOverlayColor: null,
    cupertinoOverrideTheme: null,
    extensions: null,
    inputDecorationTheme: InputDecorationTheme(
      labelStyle: AppTextStyles.p,
      hintStyle: AppTextStyles.pGrey,
      helperStyle: AppTextStyles.helperText,
      errorStyle: AppTextStyles.error,
      counterStyle: AppTextStyles.helperText,
      focusedBorder: const OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(25)),
        borderSide: BorderSide(color: AppColours.primary),
      ),
      enabledBorder: const OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(25)),
        borderSide: BorderSide(color: AppColours.borderLight),
      ),
      errorBorder: const OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(25)),
        borderSide: BorderSide(color: AppColours.red),
      ),
      focusedErrorBorder: const OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(25)),
        borderSide: BorderSide(color: AppColours.red),
      ),
      disabledBorder: const OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(25)),
        borderSide: BorderSide(color: AppColours.borderDark),
      ),
    ),
    materialTapTargetSize: null,
    pageTransitionsTheme: null,
    platform: null,
    scrollbarTheme: null,
    splashFactory: null,
    visualDensity: null,
    useMaterial3: null,
    colorScheme: null,
    colorSchemeSeed: null,
    brightness: null,
    primarySwatch: null,
    primaryColor: null,
    primaryColorLight: null,
    primaryColorDark: null,
    focusColor: null,
    hoverColor: null,
    shadowColor: null,
    canvasColor: null,
    scaffoldBackgroundColor: null,
    bottomAppBarColor: null,
    cardColor: null,
    dividerColor: null,
    highlightColor: null,
    splashColor: null,
    selectedRowColor: null,
    unselectedWidgetColor: null,
    disabledColor: null,
    secondaryHeaderColor: null,
    backgroundColor: null,
    dialogBackgroundColor: null,
    indicatorColor: null,
    hintColor: null,
    errorColor: null,
    toggleableActiveColor: null,
    fontFamily: null,
    typography: null,
    textTheme: null,
    primaryTextTheme: null,
    iconTheme: const IconThemeData(size: 15, color: AppColours.grey),
    primaryIconTheme: null,
    appBarTheme: null,
    bannerTheme: null,
    bottomAppBarTheme: null,
    bottomNavigationBarTheme: null,
    bottomSheetTheme: null,
    buttonBarTheme: null,
    buttonTheme: null,
    cardTheme: null,
    checkboxTheme: null,
    chipTheme: null,
    dataTableTheme: null,
    dialogTheme: null,
    dividerTheme: null,
    drawerTheme: null,
    elevatedButtonTheme: null,
    floatingActionButtonTheme: null,
    listTileTheme: null,
    navigationBarTheme: null,
    navigationRailTheme: null,
    outlinedButtonTheme: null,
    popupMenuTheme: null,
    progressIndicatorTheme: null,
    radioTheme: null,
    sliderTheme: null,
    snackBarTheme: null,
    switchTheme: null,
    tabBarTheme: null,
    textButtonTheme: null,
    textSelectionTheme: null,
    timePickerTheme: null,
    toggleButtonsTheme: null,
    tooltipTheme: null,
    expansionTileTheme: null,
  );

  static ThemeData darkTheme = lightTheme;

  // static ThemeData customTheme = ThemeData(
  //   applyElevationOverlayColor: null,
  //   cupertinoOverrideTheme: null,
  //   extensions: null,
  //   inputDecorationTheme: null,
  //   materialTapTargetSize: null,
  //   pageTransitionsTheme: null,
  //   platform: null,
  //   scrollbarTheme: null,
  //   splashFactory: null,
  //   visualDensity: null,
  //   useMaterial3: null,
  //   colorScheme: null,
  //   colorSchemeSeed: null,
  //   brightness: null,
  //   primarySwatch: null,
  //   primaryColor: null,
  //   primaryColorLight: null,
  //   primaryColorDark: null,
  //   focusColor: null,
  //   hoverColor: null,
  //   shadowColor: null,
  //   canvasColor: null,
  //   scaffoldBackgroundColor: null,
  //   bottomAppBarColor: null,
  //   cardColor: null,
  //   dividerColor: null,
  //   highlightColor: null,
  //   splashColor: null,
  //   selectedRowColor: null,
  //   unselectedWidgetColor: null,
  //   disabledColor: null,
  //   secondaryHeaderColor: null,
  //   backgroundColor: null,
  //   dialogBackgroundColor: null,
  //   indicatorColor: null,
  //   hintColor: null,
  //   errorColor: null,
  //   toggleableActiveColor: null,
  //   fontFamily: null,
  //   typography: null,
  //   textTheme: null,
  //   primaryTextTheme: null,
  //   iconTheme: null,
  //   primaryIconTheme: null,
  //   appBarTheme: null,
  //   bannerTheme: null,
  //   bottomAppBarTheme: null,
  //   bottomNavigationBarTheme: null,
  //   bottomSheetTheme: null,
  //   buttonBarTheme: null,
  //   buttonTheme: null,
  //   cardTheme: null,
  //   checkboxTheme: null,
  //   chipTheme: null,
  //   dataTableTheme: null,
  //   dialogTheme: null,
  //   dividerTheme: null,
  //   drawerTheme: null,
  //   elevatedButtonTheme: null,
  //   floatingActionButtonTheme: null,
  //   listTileTheme: null,
  //   navigationBarTheme: null,
  //   navigationRailTheme: null,
  //   outlinedButtonTheme: null,
  //   popupMenuTheme: null,
  //   progressIndicatorTheme: null,
  //   radioTheme: null,
  //   sliderTheme: null,
  //   snackBarTheme: null,
  //   switchTheme: null,
  //   tabBarTheme: null,
  //   textButtonTheme: null,
  //   textSelectionTheme: null,
  //   timePickerTheme: null,
  //   toggleButtonsTheme: null,
  //   tooltipTheme: null,
  //   expansionTileTheme: null,
  // );
}
